version: "4.0"

services:
  mysqldb:
    image: mysql:latest
    container_name: bookappdb
    ports:
      - "1306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=book_app
      - MYSQL_USER=bookapp
      - MYSQL_PASSWORD=bookapp